{% set name = "dimcli" %}
{% set version = "1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dimcli-{{ version }}.tar.gz
  sha256: 2933f2a3f31040778d5993956026cffbd25f1e406d885324c1dc5390ad8646bb

build:
  number: 1
  noarch: python
  entry_points:
    - dimcli = dimcli.main_cli:main_cli
    - dimcli_quicktest = dimcli.tests.quicktest:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - click
    - ipython
    - packaging
    - pandas
    - prompt-toolkit
    - pygments
    - recommonmark
    - requests
    - tqdm

test:
  imports:
    - dimcli
  commands:
    - pip check
    - dimcli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/digital-science/dimcli
  summary: Python REPL/API for accessing dimensions.ai.
  license: MIT
  license_file: LICENSE
  description: |
    Dimcli is a Python client for accessing the Dimensions Analytics API. 
    It makes it easier to authenticate against the API, send queries to it 
    and process the JSON data being returned.
  doc_url: https://digital-science.github.io/dimcli/
  dev_url: https://github.com/digital-science/dimcli

extra:
  recipe-maintainers:
    - sugatoray
